# Generated by Django 5.0.11 on 2025-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GennhrUsers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('empid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmpID', max_length=50, null=True)),
                ('plantcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('groupid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('ext_security_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('usertype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Usertype', max_length=1)),
                ('isapprover', models.BooleanField(db_column='Isapprover')),
                ('orglevel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Orglevel', max_length=255, null=True)),
                ('parentlevel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Parentlevel', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'GennHR_users',
                'managed': False,
            },
        ),
    ]
