# Generated by Django 5.0.11 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttnDaily',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('attndt', models.DateTimeField(db_column='Attndt')),
                ('wrkdivid', models.IntegerField(db_column='WrkdivID')),
                ('shiftcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Shiftcode', max_length=5)),
                ('checkin', models.DateTimeField(blank=True, db_column='Checkin', null=True)),
                ('checkout', models.DateTimeField(blank=True, db_column='Checkout', null=True)),
                ('perhrs', models.IntegerField(db_column='Perhrs')),
                ('tothrs', models.IntegerField(blank=True, db_column='Tothrs', null=True)),
                ('lshift', models.DecimalField(db_column='Lshift', decimal_places=3, max_digits=18)),
                ('regshift', models.DecimalField(db_column='Regshift', decimal_places=3, max_digits=18)),
                ('tallow', models.DecimalField(db_column='Tallow', decimal_places=2, max_digits=18)),
                ('regot', models.IntegerField(db_column='RegOT')),
                ('la', models.IntegerField(db_column='LA')),
                ('ed', models.IntegerField(db_column='ED')),
                ('laded', models.IntegerField(db_column='Laded')),
                ('edded', models.IntegerField(db_column='Edded')),
                ('mustattn', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mustattn', max_length=10)),
                ('isintimatedleave', models.BooleanField(db_column='IsIntimatedLeave')),
                ('islock', models.BooleanField(db_column='Islock')),
                ('wgen', models.BooleanField(db_column='Wgen')),
                ('mgen', models.BooleanField(db_column='Mgen')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=10, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=10, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
                ('break1', models.DateTimeField(blank=True, db_column='Break1', null=True)),
                ('break2', models.DateTimeField(blank=True, db_column='Break2', null=True)),
                ('fnshift', models.DecimalField(db_column='FNshift', decimal_places=3, max_digits=18)),
                ('anshift', models.DecimalField(db_column='ANshift', decimal_places=3, max_digits=18)),
                ('fnlcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FNLcode', max_length=5)),
                ('anlcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ANLcode', max_length=5)),
            ],
            options={
                'db_table': 'Attn_Daily',
                'managed': False,
            },
        ),
    ]
