# Generated by Django 5.0.11 on 2025-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0002_attndaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntAddress',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('atype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Atype', max_length=1)),
                ('platno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Platno', max_length=50, null=True)),
                ('streetname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Streetname', max_length=150, null=True)),
                ('townname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Townname', max_length=50, null=True)),
                ('locid', models.IntegerField(blank=True, db_column='LocID', null=True)),
                ('locname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Locname', max_length=50, null=True)),
                ('talukname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Talukname', max_length=50, null=True)),
                ('districtname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Districtname', max_length=50, null=True)),
                ('statename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Statename', max_length=50, null=True)),
                ('countryname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Countryname', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nationality', max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pincode', max_length=10, null=True)),
                ('nativeps', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NativePS', max_length=30, null=True)),
                ('docname', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Docname', null=True)),
                ('appstatus', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Appstatus', max_length=20)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=50, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Ent_Address',
                'managed': False,
            },
        ),
    ]
