# Generated by Django 5.0.11 on 2025-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0003_entaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasDocuments',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('docname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Docname', max_length=30)),
                ('doccatg', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Doccatg', max_length=20)),
                ('ispf', models.BooleanField(db_column='Ispf')),
                ('pfcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pfcode', max_length=1, null=True)),
                ('isexpiry', models.BooleanField(db_column='Isexpiry')),
                ('alertbefore', models.IntegerField(db_column='Alertbefore')),
                ('chkid', models.IntegerField(blank=True, db_column='ChkID', null=True)),
                ('isactive', models.BooleanField(db_column='Isactive')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasEmpDocuments',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('docid', models.IntegerField(db_column='DocID')),
                ('docno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Docno', max_length=20, null=True)),
                ('docname', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Docname', null=True)),
                ('chkid', models.IntegerField(blank=True, db_column='ChkID', null=True)),
                ('expirydt', models.DateField(blank=True, db_column='Expirydt', null=True)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Emp_Documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasPlantleave',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('lcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lcode', max_length=5)),
                ('lname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lname', max_length=20)),
                ('isnh', models.BooleanField(db_column='IsNH')),
                ('isph', models.BooleanField(db_column='IsPH')),
                ('maxleave', models.IntegerField(db_column='Maxleave')),
                ('isencash', models.BooleanField(db_column='IsEncash')),
                ('validdays', models.DecimalField(db_column='Validdays', decimal_places=2, max_digits=18)),
                ('isactive', models.BooleanField(db_column='Isactive')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Plantleave',
                'managed': False,
            },
        ),
    ]
