# Generated by Django 5.0.11 on 2025-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0004_masdocuments_masempdocuments_masplantleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasChklist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('chklistname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Chklistname', max_length=30)),
                ('chktype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Chktype', max_length=10)),
                ('isreq', models.BooleanField(db_column='Isreq')),
                ('isactive', models.BooleanField(db_column='Isactive')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=18, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=10, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Chklist',
                'managed': False,
            },
        ),
    ]
