# Generated by Django 5.0.11 on 2025-03-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0005_maschklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GennhrAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('ip', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40)),
                ('user', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('table', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('action', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=250)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'GennHR_audit',
                'managed': False,
            },
        ),
    ]
