# Generated by Django 5.0.11 on 2025-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0008_entmsalary_masbank_masdedheads_masempsalsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntLoanappl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('loanreqdt', models.DateTimeField(db_column='Loanreqdt')),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('loanamt', models.DecimalField(db_column='Loanamt', decimal_places=2, max_digits=18)),
                ('noofdues', models.IntegerField(db_column='Noofdues')),
                ('loanemi', models.DecimalField(db_column='Loanemi', decimal_places=2, max_digits=18)),
                ('dedmode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dedmode', max_length=20)),
                ('dedstartfrom', models.DateTimeField(db_column='Dedstartfrom')),
                ('remarks', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', max_length=100, null=True)),
                ('sanctionamt', models.DecimalField(db_column='Sanctionamt', decimal_places=2, max_digits=18)),
                ('sanctionemi', models.DecimalField(db_column='Sanctionemi', decimal_places=2, max_digits=18)),
                ('sanctiondues', models.IntegerField(db_column='Sanctiondues')),
                ('intrate', models.DecimalField(db_column='Intrate', decimal_places=2, max_digits=18)),
                ('intamt', models.DecimalField(db_column='Intamt', decimal_places=2, max_digits=18)),
                ('sanctionnetamt', models.DecimalField(db_column='Sanctionnetamt', decimal_places=2, max_digits=18)),
                ('appstatus', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Appstatus', max_length=50)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Ent_Loanappl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasLoan',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('loanname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Loanname', max_length=50)),
                ('isactive', models.BooleanField(db_column='Isactive')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'mas_loan',
                'managed': False,
            },
        ),
    ]
