# Generated by Django 5.0.11 on 2025-03-27 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0009_entloanappl_masloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntEmpExpenses',
            fields=[
                ('claimid', models.AutoField(db_column='ClaimID', primary_key=True, serialize=False)),
                ('claimdt', models.DateField(db_column='Claimdt')),
                ('empid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmpID', max_length=10)),
                ('claimamount', models.DecimalField(db_column='Claimamount', decimal_places=2, max_digits=10)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg'])])),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('appstatus', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Appstatus', max_length=20, null=True)),
                ('appamount', models.DecimalField(blank=True, db_column='Appamount', decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', null=True)),
                ('paidamount', models.DecimalField(blank=True, db_column='Paidamount', decimal_places=2, max_digits=10, null=True)),
                ('createdby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=50)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updateby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updateby', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='Updatedate', null=True)),
            ],
            options={
                'db_table': 'Ent_Emp_Expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntEmpLeaveappl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('lfrom', models.DateTimeField(db_column='LFrom')),
                ('lto', models.DateTimeField(db_column='Lto')),
                ('lcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lcode', max_length=5)),
                ('leavebal', models.DecimalField(db_column='Leavebal', decimal_places=2, max_digits=18)),
                ('fromfn', models.BooleanField(db_column='FromFN')),
                ('froman', models.BooleanField(db_column='FromAN')),
                ('tofn', models.BooleanField(db_column='ToFN')),
                ('toan', models.BooleanField(db_column='ToAN')),
                ('totldays', models.DecimalField(db_column='Totldays', decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50, null=True)),
                ('appstatus', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Appstatus', default='Pending', max_length=10)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
                ('attachment', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'Ent_Emp_Leaveappl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntMleave',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('smonthid', models.IntegerField(blank=True, db_column='SmonthID', null=True)),
                ('smonth', models.DateTimeField(blank=True, db_column='Smonth', null=True)),
                ('mstart', models.DateTimeField(blank=True, db_column='Mstart', null=True)),
                ('mend', models.DateTimeField(blank=True, db_column='Mend', null=True)),
                ('plantcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10, null=True)),
                ('empid', models.IntegerField(blank=True, db_column='EmpID', null=True)),
                ('clop', models.DecimalField(db_column='CLop', decimal_places=2, max_digits=18)),
                ('clcr', models.DecimalField(blank=True, db_column='CLcr', decimal_places=2, max_digits=18, null=True)),
                ('clutil', models.DecimalField(db_column='CLutil', decimal_places=2, max_digits=18)),
                ('clbal', models.DecimalField(blank=True, db_column='CLbal', decimal_places=2, max_digits=20, null=True)),
                ('elop', models.DecimalField(db_column='ELop', decimal_places=2, max_digits=18)),
                ('elcr', models.DecimalField(blank=True, db_column='ELcr', decimal_places=2, max_digits=18, null=True)),
                ('elutil', models.DecimalField(db_column='ELutil', decimal_places=0, max_digits=18)),
                ('elbal', models.DecimalField(blank=True, db_column='ELbal', decimal_places=2, max_digits=21, null=True)),
                ('mlop', models.DecimalField(db_column='MLop', decimal_places=2, max_digits=18)),
                ('mlcr', models.DecimalField(blank=True, db_column='MLcr', decimal_places=2, max_digits=18, null=True)),
                ('mlutil', models.DecimalField(db_column='MLutil', decimal_places=2, max_digits=18)),
                ('mlbal', models.DecimalField(blank=True, db_column='MLbal', decimal_places=2, max_digits=20, null=True)),
                ('slop', models.DecimalField(db_column='SLop', decimal_places=2, max_digits=18)),
                ('slcr', models.DecimalField(blank=True, db_column='SLcr', decimal_places=2, max_digits=18, null=True)),
                ('slutil', models.DecimalField(db_column='SLutil', decimal_places=2, max_digits=18)),
                ('slbal', models.DecimalField(blank=True, db_column='SLbal', decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'Ent_Mleave',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasEmpLeave',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('lyear', models.IntegerField(db_column='Lyear')),
                ('lcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lcode', max_length=5)),
                ('lopen', models.DecimalField(db_column='Lopen', decimal_places=2, max_digits=18)),
                ('lcredit', models.DecimalField(blank=True, db_column='Lcredit', decimal_places=2, max_digits=18, null=True)),
                ('lutil', models.DecimalField(db_column='Lutil', decimal_places=2, max_digits=18)),
                ('lncash', models.DecimalField(db_column='Lncash', decimal_places=2, max_digits=18)),
                ('lbal', models.DecimalField(blank=True, db_column='Lbal', decimal_places=2, max_digits=21, null=True)),
                ('isactive', models.BooleanField(db_column='Isactive')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Emp_Leave',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasExpenses',
            fields=[
                ('expid', models.AutoField(db_column='ExpID', primary_key=True, serialize=False)),
                ('expname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Expname', max_length=100)),
                ('isactive', models.BooleanField(blank=True, db_column='Isactive', null=True)),
                ('createdby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=50)),
                ('createddate', models.DateTimeField(db_column='Createddate')),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=50, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Mas_Expenses',
                'managed': False,
            },
        ),
    ]
