# Generated by Django 5.0.11 on 2025-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0010_entempexpenses_entempleaveappl_entmleave_masempleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntLoanschedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('loanid', models.IntegerField(db_column='LoanID')),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('deddt', models.DateField(db_column='Deddt')),
                ('dedmode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dedmode', max_length=10)),
                ('dueamt', models.DecimalField(db_column='Dueamt', decimal_places=2, max_digits=18)),
                ('rded', models.DecimalField(db_column='Rded', decimal_places=2, max_digits=18)),
                ('cash1', models.DecimalField(db_column='Cash1', decimal_places=2, max_digits=18)),
                ('cash2', models.DecimalField(db_column='Cash2', decimal_places=2, max_digits=18)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=10)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Ent_Loanschedule',
                'managed': False,
            },
        ),
    ]
