# Generated by Django 5.0.11 on 2025-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0011_entloanschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntEmpLeavedetails',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('laid', models.IntegerField(db_column='LAID')),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('ldate', models.DateTimeField(db_column='Ldate')),
                ('fnlcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FNLcode', max_length=5)),
                ('anlcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ANLcode', max_length=5)),
                ('fn', models.BooleanField(db_column='FN')),
                ('an', models.BooleanField(db_column='AN')),
                ('appstatus', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Appstatus')),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Ent_Emp_Leavedetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntLoanmas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('appid', models.IntegerField(db_column='AppID')),
                ('plantcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plantcode', max_length=10)),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('loanno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Loanno', max_length=10)),
                ('loandt', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Loandt', max_length=10)),
                ('lnameid', models.IntegerField(db_column='LnameID')),
                ('loanamt', models.DecimalField(db_column='Loanamt', decimal_places=2, max_digits=18)),
                ('intrate', models.DecimalField(db_column='Intrate', decimal_places=2, max_digits=18)),
                ('loantenure', models.IntegerField(db_column='Loantenure')),
                ('loanemi', models.DecimalField(db_column='LoanEMI', decimal_places=2, max_digits=18)),
                ('intamt', models.DecimalField(db_column='Intamt', decimal_places=2, max_digits=18)),
                ('totalamt', models.DecimalField(db_column='Totalamt', decimal_places=2, max_digits=18)),
                ('dedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dedby', max_length=20, null=True)),
                ('recstarton', models.DateField(db_column='Recstarton')),
                ('recendon', models.DateField(db_column='Recendon')),
                ('recdamt', models.DecimalField(db_column='Recdamt', decimal_places=2, max_digits=18)),
                ('foreclosureamt', models.DecimalField(db_column='Foreclosureamt', decimal_places=2, max_digits=18)),
                ('baddebit', models.DecimalField(db_column='Baddebit', decimal_places=2, max_digits=18)),
                ('completedon', models.DateField(blank=True, db_column='Completedon', null=True)),
                ('balamt', models.DecimalField(db_column='Balamt', decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', null=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=10)),
                ('noofdues', models.DecimalField(db_column='Noofdues', decimal_places=2, max_digits=18)),
                ('createdby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Createdby', max_length=15, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='Createddate', null=True)),
                ('updatedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updatedby', max_length=15, null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='Updateddate', null=True)),
            ],
            options={
                'db_table': 'Ent_Loanmas',
                'managed': False,
            },
        ),
    ]
